import { GroceryItem, Recipe, ShoppingItem, UserProfile, WasteRecord } from './types';

// Format helper relative to today
export const getOffsetDate = (daysOffset: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

export const defaultUser: UserProfile = {
  name: 'Ananya Sharma',
  email: 'ananya.sharma@example.com',
  householdSize: 3,
  currency: '₹',
  isAuthenticated: true,
  joinedDate: '2025-01-15',
  dietaryPreferences: ['Vegetarian'],
};

export const initialGroceries: GroceryItem[] = [
  {
    id: 'g-1',
    name: 'Fresh Cow Milk',
    category: 'Dairy',
    quantity: 1,
    unit: 'Litre',
    purchaseDate: getOffsetDate(-4),
    expiryDate: getOffsetDate(1), // Tomorrow!
    price: 45,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80',
    notes: 'Pasteurized whole milk, best consumed cold or boiled',
  },
  {
    id: 'g-2',
    name: 'Ripe Red Tomatoes',
    category: 'Vegetables',
    quantity: 500,
    unit: 'grams',
    purchaseDate: getOffsetDate(-5),
    expiryDate: getOffsetDate(2), // 2 days
    price: 35,
    storageLocation: 'Countertop',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&auto=format&fit=crop&q=80',
    notes: 'Local organic farm fresh tomatoes',
  },
  {
    id: 'g-3',
    name: 'Whole Wheat Sandwich Bread',
    category: 'Bakery',
    quantity: 1,
    unit: 'Loaf',
    purchaseDate: getOffsetDate(-3),
    expiryDate: getOffsetDate(3), // 3 days
    price: 50,
    storageLocation: 'Pantry',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=80',
    notes: 'Zero preservatives, artisanal brown bread',
  },
  {
    id: 'g-4',
    name: 'Fresh Farm Spinach',
    category: 'Vegetables',
    quantity: 250,
    unit: 'grams',
    purchaseDate: getOffsetDate(-4),
    expiryDate: getOffsetDate(1), // Tomorrow!
    price: 25,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300&auto=format&fit=crop&q=80',
    notes: 'Washed and trimmed baby palak leaves',
  },
  {
    id: 'g-5',
    name: 'Fresh Farm Eggs',
    category: 'Dairy',
    quantity: 6,
    unit: 'pieces',
    purchaseDate: getOffsetDate(-6),
    expiryDate: getOffsetDate(5), // 5 days
    price: 60,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=300&auto=format&fit=crop&q=80',
    notes: 'Free-range brown eggs',
  },
  {
    id: 'g-6',
    name: 'Fresh Paneer (Cottage Cheese)',
    category: 'Dairy',
    quantity: 200,
    unit: 'grams',
    purchaseDate: getOffsetDate(-3),
    expiryDate: getOffsetDate(2), // 2 days
    price: 90,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300&auto=format&fit=crop&q=80',
    notes: 'Soft malai paneer',
  },
  {
    id: 'g-7',
    name: 'Crisp Royal Gala Apples',
    category: 'Fruits',
    quantity: 1,
    unit: 'kg',
    purchaseDate: getOffsetDate(-2),
    expiryDate: getOffsetDate(6), // 6 days
    price: 120,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-8',
    name: 'Greek Plain Yogurt',
    category: 'Dairy',
    quantity: 400,
    unit: 'grams',
    purchaseDate: getOffsetDate(-3),
    expiryDate: getOffsetDate(4), // 4 days
    price: 75,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-9',
    name: 'Yellow Bell Peppers',
    category: 'Vegetables',
    quantity: 2,
    unit: 'pieces',
    purchaseDate: getOffsetDate(-3),
    expiryDate: getOffsetDate(3), // 3 days
    price: 40,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-10',
    name: 'Chicken Breast Cutlets',
    category: 'Meat',
    quantity: 500,
    unit: 'grams',
    purchaseDate: getOffsetDate(-1),
    expiryDate: getOffsetDate(2), // 2 days
    price: 220,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-11',
    name: 'Organic Table Butter',
    category: 'Dairy',
    quantity: 100,
    unit: 'grams',
    purchaseDate: getOffsetDate(-14),
    expiryDate: getOffsetDate(-1), // Expired 1 day ago!
    price: 60,
    storageLocation: 'Fridge',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-12',
    name: 'Basmati Long Grain Rice',
    category: 'Grains',
    quantity: 3,
    unit: 'kg',
    purchaseDate: getOffsetDate(-15),
    expiryDate: getOffsetDate(90), // 90 days
    price: 180,
    storageLocation: 'Pantry',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'g-13',
    name: 'Rolled Oats',
    category: 'Grains',
    quantity: 1,
    unit: 'kg',
    purchaseDate: getOffsetDate(-20),
    expiryDate: getOffsetDate(120),
    price: 95,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-14',
    name: 'Sharp Cheddar Cheese Block',
    category: 'Dairy',
    quantity: 200,
    unit: 'grams',
    purchaseDate: getOffsetDate(-5),
    expiryDate: getOffsetDate(12),
    price: 140,
    storageLocation: 'Fridge',
  },
  {
    id: 'g-15',
    name: 'Frozen Green Sweet Peas',
    category: 'Frozen',
    quantity: 500,
    unit: 'grams',
    purchaseDate: getOffsetDate(-10),
    expiryDate: getOffsetDate(150),
    price: 65,
    storageLocation: 'Freezer',
  },
  {
    id: 'g-16',
    name: 'Extra Virgin Cold-Pressed Olive Oil',
    category: 'Other',
    quantity: 1,
    unit: 'Litre',
    purchaseDate: getOffsetDate(-30),
    expiryDate: getOffsetDate(180),
    price: 450,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-17',
    name: 'Sweet Bananas',
    category: 'Fruits',
    quantity: 6,
    unit: 'pieces',
    purchaseDate: getOffsetDate(-3),
    expiryDate: getOffsetDate(2),
    price: 40,
    storageLocation: 'Countertop',
  },
  {
    id: 'g-18',
    name: 'Orange Juice Bottle',
    category: 'Beverages',
    quantity: 1,
    unit: 'Litre',
    purchaseDate: getOffsetDate(-2),
    expiryDate: getOffsetDate(4),
    price: 110,
    storageLocation: 'Fridge',
  },
  {
    id: 'g-19',
    name: 'Red Onions Sack',
    category: 'Vegetables',
    quantity: 2,
    unit: 'kg',
    purchaseDate: getOffsetDate(-5),
    expiryDate: getOffsetDate(25),
    price: 70,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-20',
    name: 'Baby Carrots',
    category: 'Vegetables',
    quantity: 500,
    unit: 'grams',
    purchaseDate: getOffsetDate(-2),
    expiryDate: getOffsetDate(8),
    price: 30,
    storageLocation: 'Fridge',
  },
  {
    id: 'g-21',
    name: 'Dark Roasted Coffee Beans',
    category: 'Beverages',
    quantity: 250,
    unit: 'grams',
    purchaseDate: getOffsetDate(-10),
    expiryDate: getOffsetDate(60),
    price: 320,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-22',
    name: 'Fusilli Durum Wheat Pasta',
    category: 'Grains',
    quantity: 500,
    unit: 'grams',
    purchaseDate: getOffsetDate(-12),
    expiryDate: getOffsetDate(210),
    price: 70,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-23',
    name: 'Dark Cocoa Chocolate (70%)',
    category: 'Snacks',
    quantity: 100,
    unit: 'grams',
    purchaseDate: getOffsetDate(-8),
    expiryDate: getOffsetDate(45),
    price: 80,
    storageLocation: 'Pantry',
  },
  {
    id: 'g-24',
    name: 'Baby Potatoes',
    category: 'Vegetables',
    quantity: 1,
    unit: 'kg',
    purchaseDate: getOffsetDate(-4),
    expiryDate: getOffsetDate(20),
    price: 40,
    storageLocation: 'Pantry',
  },
];

export const initialWasteRecords: WasteRecord[] = [
  {
    id: 'w-1',
    itemName: 'Organic Table Butter',
    category: 'Dairy',
    quantity: 100,
    unit: 'grams',
    price: 60,
    reason: 'Expired',
    date: getOffsetDate(-1),
  },
  {
    id: 'w-2',
    itemName: 'Coriander Leaves & Mint',
    category: 'Vegetables',
    quantity: 1,
    unit: 'bunch',
    price: 25,
    reason: 'Spoiled',
    date: getOffsetDate(-6),
  },
  {
    id: 'w-3',
    itemName: 'Leftover Vegetable Curry',
    category: 'Other',
    quantity: 1,
    unit: 'bowl',
    price: 50,
    reason: 'Cooked too much',
    date: getOffsetDate(-12),
  },
  {
    id: 'w-4',
    itemName: 'French Loaf Bread',
    category: 'Bakery',
    quantity: 1,
    unit: 'piece',
    price: 45,
    reason: 'Expired',
    date: getOffsetDate(-18),
  },
];

export const initialShoppingList: ShoppingItem[] = [
  {
    id: 's-1',
    name: 'Fresh Cow Milk',
    category: 'Dairy',
    quantity: 1,
    unit: 'Litre',
    estimatedPrice: 45,
    isCompleted: false,
    notes: 'Usually consumed every 4-5 days. Needed tomorrow.',
    addedFromRecommendation: true,
  },
  {
    id: 's-2',
    name: 'Almond Butter',
    category: 'Snacks',
    quantity: 1,
    unit: 'jar',
    estimatedPrice: 280,
    isCompleted: false,
    notes: 'Breakfast pantry replenishment',
  },
  {
    id: 's-3',
    name: 'Garlic Bulbs',
    category: 'Vegetables',
    quantity: 250,
    unit: 'grams',
    estimatedPrice: 35,
    isCompleted: true,
    notes: 'Bought from local vendor',
  },
];

export const smartRecipeLibrary: Recipe[] = [
  {
    id: 'r-1',
    title: 'Egg & Tomato Breakfast Toast',
    description: 'A quick, savory high-protein breakfast utilizing eggs, fresh juicy tomatoes, and toasted sandwich bread before they reach expiry.',
    prepTime: '12 mins',
    difficulty: 'Easy',
    servings: 2,
    calories: 320,
    tags: ['Breakfast', 'High Protein', 'Quick'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    ingredients: [
      { name: 'Eggs', amount: '2 pieces' },
      { name: 'Tomatoes', amount: '2 medium' },
      { name: 'Sandwich Bread', amount: '2 slices' },
      { name: 'Butter or Olive Oil', amount: '1 tsp' },
      { name: 'Black Pepper & Salt', amount: 'pinch' },
    ],
    instructions: [
      'Slice tomatoes into rounds and lightly sear in a skillet with a dash of olive oil and pinch of salt until softened.',
      'In the same skillet, whisk and scramble the eggs gently on low heat until fluffy.',
      'Toast your sandwich bread slices until golden brown and fragrant.',
      'Layer warm tomato slices over toast, spoon the soft scrambled eggs on top, and season with crushed black pepper.',
    ],
    expiringIngredientsUsed: ['Eggs', 'Tomatoes', 'Bread'],
  },
  {
    id: 'r-2',
    title: 'Garlic Spinach & Paneer Scramble (Bhurji)',
    description: 'Fragrant crumbled paneer sautéed with iron-rich fresh spinach, onions, and mild spices. Perfect with roti or whole wheat toast.',
    prepTime: '15 mins',
    difficulty: 'Easy',
    servings: 2,
    calories: 290,
    tags: ['Vegetarian', 'Quick Dinner', 'Keto-Friendly'],
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Chop fresh spinach finely and crumble the fresh paneer with your hands.',
      'Heat 1 tbsp oil in a pan, add cumin seeds, sliced onions, and minced garlic. Sauté until translucent.',
      'Add turmeric, chili powder, and tomatoes. Cook until soft.',
      'Toss in chopped spinach and sauté for 2 minutes until wilted.',
      'Fold in the crumbled paneer, adjust salt, and gently stir for 3 minutes. Serve hot!',
    ],
    ingredients: [
      { name: 'Spinach', amount: '200 grams' },
      { name: 'Paneer', amount: '200 grams' },
      { name: 'Tomatoes', amount: '1 piece' },
      { name: 'Onions', amount: '1 piece' },
    ],
    expiringIngredientsUsed: ['Spinach', 'Paneer', 'Tomatoes'],
  },
  {
    id: 'r-3',
    title: 'One-Skillet Chicken & Bell Pepper Fajita Bowl',
    description: 'Juicy seared chicken breast strips with charred sweet yellow bell peppers and warming taco seasonings.',
    prepTime: '20 mins',
    difficulty: 'Medium',
    servings: 3,
    calories: 380,
    tags: ['Dinner', 'Low Carb', 'Meal Prep'],
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Slice chicken breast into bite-sized strips and season with paprika, cumin, salt, and olive oil.',
      'Slice yellow bell peppers and onions into long strips.',
      'Heat a heavy pan on high heat. Sear chicken strips for 6-8 minutes until golden and cooked through. Remove to a plate.',
      'Toss bell peppers and onions in the remaining pan juices for 4 minutes until blistered yet crunchy.',
      'Return chicken to the pan, toss together, and serve with rice or tortillas.',
    ],
    ingredients: [
      { name: 'Chicken Breast', amount: '500 grams' },
      { name: 'Bell Peppers', amount: '2 pieces' },
      { name: 'Onions', amount: '1 piece' },
      { name: 'Olive Oil', amount: '1 tbsp' },
    ],
    expiringIngredientsUsed: ['Chicken Breast', 'Bell Peppers'],
  },
  {
    id: 'r-4',
    title: 'Creamy Golden Banana & Apple Parfait',
    description: 'Use spotty sweet bananas and crisp sliced apples with chilled Greek yogurt, honey, and toasted oats.',
    prepTime: '8 mins',
    difficulty: 'Easy',
    servings: 1,
    calories: 240,
    tags: ['Snack', 'No-Cook', 'Dessert'],
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'Slice bananas and apples into bite-sized pieces.',
      'In a glass jar or bowl, add 3 generous spoons of Greek yogurt.',
      'Layer sliced bananas, apples, a sprinkle of rolled oats, and a drizzle of honey.',
      'Repeat with a second layer and top with dark chocolate shavings or cinnamon.',
    ],
    ingredients: [
      { name: 'Bananas', amount: '2 pieces' },
      { name: 'Apples', amount: '1 piece' },
      { name: 'Greek Yogurt', amount: '200 grams' },
      { name: 'Rolled Oats', amount: '2 tbsp' },
    ],
    expiringIngredientsUsed: ['Bananas', 'Greek Yogurt', 'Apples'],
  },
  {
    id: 'r-5',
    title: 'Rustic French Toast with Warm Spiced Milk',
    description: 'Revive day-old bread by soaking it in a spiced egg-milk custard and pan-frying in butter to golden perfection.',
    prepTime: '15 mins',
    difficulty: 'Easy',
    servings: 2,
    calories: 340,
    tags: ['Comfort Food', 'Classic', 'Zero Waste'],
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-00a0975f2144?w=500&auto=format&fit=crop&q=80',
    instructions: [
      'In a shallow wide dish, whisk together 2 eggs, 1/2 cup milk, pinch of cinnamon, and 1 tsp sugar.',
      'Dip bread slices into the egg custard for 15 seconds per side until soaked.',
      'Melt butter in a nonstick pan over medium heat. Fry bread slices for 3 minutes on each side until golden.',
      'Serve warm with sliced fruit and a drizzle of maple syrup or honey.',
    ],
    ingredients: [
      { name: 'Sandwich Bread', amount: '4 slices' },
      { name: 'Milk', amount: '1/2 cup' },
      { name: 'Eggs', amount: '2 pieces' },
      { name: 'Butter', amount: '1 tbsp' },
    ],
    expiringIngredientsUsed: ['Bread', 'Milk', 'Eggs'],
  },
];
